CREATE TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" 
   (	"ID_FILEPATHS" VARCHAR2(40) NOT NULL ENABLE, 
	"ITEM" NVARCHAR2(100) NOT NULL ENABLE, 
	"ITEM_PK" VARCHAR2(40) NOT NULL ENABLE, 
	"PATH" NVARCHAR2(255) NOT NULL ENABLE, 
	"FILENAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"TYPE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_FILE_PATH_ID" PRIMARY KEY ("ID_FILEPATHS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "NETBAISDATA"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "NETBAISDATA" ;
  CREATE UNIQUE INDEX "JSZJJ_XZSP_QZ"."PK_FILE_PATH_ID" ON "JSZJJ_XZSP_QZ"."FILE_PATHS" ("ID_FILEPATHS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "NETBAISDATA" ;
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("ID_FILEPATHS" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("ITEM" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("ITEM_PK" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "JSZJJ_XZSP_QZ"."FILE_PATHS" ADD CONSTRAINT "PK_FILE_PATH_ID" PRIMARY KEY ("ID_FILEPATHS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "NETBAISDATA"  ENABLE;
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."ID_FILEPATHS" IS '本表主键';
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."ITEM" IS '事项类型（事项表的表名）';
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."ITEM_PK" IS '办件主键';
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."PATH" IS '文件路径';
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."FILENAME" IS '文件名';
   COMMENT ON COLUMN "JSZJJ_XZSP_QZ"."FILE_PATHS"."TYPE" IS '文件类型.0:单个附件,1:该办件的所有附件打包';